### ISSUE TITLE
Cannot run from the same machine running the mail server itself

### ISSUE THREAD

**Issue by ghost** [JanMaartenvanDoorn/Laelaps#1]
After docker-compose up I get errors that the (mail) port is already in use, which is correct since it is used by the mail server.
```
Error response from daemon: driver failed programming external connectivity on endpoint laelaps-laelaps-1 (d9724ed73e44ad742c79a1cdacc119f50757171de20ac02b0152ad7b234e9689): Error starting userland proxy: listen tcp4 0.0.0.0:993: bind: address already in use
```
What is the idea/function of the `userland proxy`?

**Comment by JanMaartenvanDoorn** [comment]
See comment under #2

**Comment by ghost** [comment]
Thanks for looking into the issue! Using `python -m laelaps` I was able to successfully run laelaps on the same machine running my mail server :)
